version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      #- restore_cache:
      - run: sudo apt install cmake build-essential libmbedtls-dev jq
      - run: npm i
      - run: npm t

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
